### ISSUE TITLE
Win7x64 & .NET4.6.1上报错

### ISSUE THREAD

**Issue by luboq** [KNCheung/RecycleBinHelper#1]
我装有.NET Framework 4.6.1
是环境不对？程序bug？还是不支持Win7？

![](http://onuia4d7l.bkt.clouddn.com/2017_04_05_20170405080857.png)

**Comment by P4SSER8Y** [comment]
非常感谢您的回复！最近比较忙，没怎么看 Github 和这个论坛……

最后发现是微软的 Bug……这个 Bug 只会在 Win 8 以上系统编译，再在 Win 7 上运行才会出现，反过来就没问题，我是没想明白为啥了……而我所用到的 API 是在 Win 2000 就出现的了。

运行环境也没问题，我在.NET 4.0上编译的。
